=== zknicker/StudentMeetup/MeetupPrototype/xml/event.dtd
<!ELEMENT events (event+)>
<!ELEMENT event (title,description,location,category,threshold,status)>
<!ATTLIST event 
	id			CDATA	#REQUIRED
	startTime	CDATA	#REQUIRED
	endTime		CDATA 	#REQUIRED
>

<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT threshold (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== zknicker/StudentMeetup/xml/event.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE events SYSTEM "event.dtd">
<events>
	<event id="12345" startTime="1230716348761" endTime="1230716348761">
		<title>Baseball Game</title>
		<description>This is a fun American game.</description>
		<location>The oval.</location>
		<category>Sports</category>
		<threshold>12</threshold>
		<status>3</status>
	</event>
	<event id="123456" startTime="1230716348761" endTime="1230716348761">
		<title>Baseball Game</title>
		<description>This is a fun American game.</description>
		<location>The oval.</location>
		<category>Sports</category>
		<threshold>12</threshold>
		<status>3</status>
	</event>
</events>
