=== zknicker/StudentMeetup/xml/user.dtd
<!ELEMENT users (user+)>
<!ELEMENT user (username,firstName,lastName,password,email,preferences)>
<!ATTLIST user 
	id			CDATA	#REQUIRED
>

<!ELEMENT username (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT preferences (emailNotifications)>
<!ELEMENT emailNotifications (#PCDATA)>

=== zknicker/StudentMeetup/xml/user.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE users SYSTEM "user.dtd">
<users>
	<user id="889923">
		<username>Zach</username>
		<firstName>Zach</firstName>
		<lastName>Knickerbocker</lastName>
		<password>324234234234</password>
		<email>zknicker@gmail.com</email>
        <rating>89</rating>
		<preferences>
			<emailNotifications>true</emailNotifications>
		</preferences>
	</user>
	<user id="8899234567">
		<username>Dave</username>
		<firstName>Dave</firstName>
		<lastName>Holmes</lastName>
		<password>mypass</password>
		<email>holmes@somesite.com</email>
        <rating>89</rating>
		<preferences>
			<emailNotifications>false</emailNotifications>
		</preferences>
	</user>
</users>
